version: "3.7"

services:
  web:
    container_name: accounts_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/accounts_service/
    ports:
      - 8000:8000
    env_file:
      - env

    depends_on:
      - db
  db:
    container_name: accounts_db_container
    image: postgres:10.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - env.db

volumes:
  postgres_data:
