version: "3.7"

services:
  gateway:
    container_name: apollogateway_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/gateway"
      - "/gateway/node_modules" # mounts an empty folder for yarn to install dependencies on the image
    ports:
      - "5000:5000" # defines port mapping for the gateway

    networks:
      - gatewaynet

networks:
  gatewaynet:
