version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/employees_service/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - ENGINE=django.db.backends.postgresql
      - DB_NAME=ariadne_db
      - DB_USER=ariadne
      - PASSWORD=ariadne
      - HOST=db
      - PORT=5432
      - DATABASE=postgres

    depends_on:
      - db
  db:
    image: postgres:10.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ariadne
      - POSTGRES_PASSWORD=ariadne
      - POSTGRES_DB=ariadne_db

volumes:
  postgres_data:
